from .triplet import TripletLoss,CrossEntropyLabelSmooth,CenterLoss

#from .alexnet import SetNet
#from .gaitset_without_hpm_3 import SetNet
#from .gaitset_without_hpm_4 import SetNet
#from .gaitset_without_hpm_2 import SetNet
#from .gaitset_without_hpm_5 import SetNet
#from .conv3dNet import SetNet
#from .conv3dNet_v2 import SetNet
#from .conv3dNet_v3 import SetNet
#from .conv3dNet_v4 import SetNet
#from .conv3dNet_v5 import SetNet
#from .conv3dNet_v6 import SetNet
#from .conv3dNet_without_CoST_v6 import SetNet
#from .conv3dNet_2streams import SetNet3d
from .gaitset_2streams_v2 import SetNet
#from .gaitset_RAL_streams import SetNet
#from .CoST_2streams import SetNet3d
#from .M3D_2streams import SetNet3d
#from .M3D_RAL_2streams import SetNet3d
from .M3D_RAL_2streams_v3 import SetNet3d
#from .gaitset_2streams import SetNet
#from .gaitset import SetNet
#from .gaitset_pyramid import SetNet
#from .vgg_16 import SetNet
